<?php
/**
 * Product Update JS Form
 */
?>
<?php $_helper = Mage::helper('ajaxcart') ?>
<?php if($_helper->getConfig('enable')):?>
<script type="text/javascript">
    if (typeof productAddToCartForm == "undefined") {
        var productAddToCartForm = new VarienForm('product_addtocart_form');
    } else {
        productAddToCartForm = new VarienForm('product_addtocart_form');
    }
	productAddToCartForm.submit = function(button, url) {
		if (this.validator.validate()) {
			var form = this.form;
			var oldUrl = form.action;
			if (url) {
			   form.action = url;
			}
			var e = null;
			try {
			//Adding to cart animation
            <?php if ($_helper->getConfig('allow_animation')): ?>
                <?php if ($_helper->getConfig('animation_target')): ?>
                    var target = $$('.top-link-cart').first();
                    if (target) target = $(target.parentNode);
                <?php else: ?>
                    var target = $$('<?php echo $_helper->getMiniCartClass() ? $_helper->getMiniCartClass() : 'none' ?>').first();
                <?php endif ?>
            if (target && $('ajaxcart-content').down('.product-image')) {
                new AjaxcartAnimation('ajaxcart-animation', target, true, $('ajaxcart-content').down('.product-image'),<?php echo $this->helper('ajaxcart')->getConfig('auto_scroll') ? 'true' : 'false' ?>, function() {
                    ajaxcart.allowFinish = true;
                    if (ajaxcart.responseCache) ajaxcart.addToCartFinish(ajaxcart.responseCache);
                });
                ajaxcart.allowFinish = false;
            }
            <?php endif ?>
				    //var proElement = ajaxcartEvent.element().up('.product-options-bottom');


                    var inputElements = Form.getElements(form);
                    var formElements = [];
                    var el;
                    for (var i=0; i<inputElements.length; i++) {
                        el = inputElements[i];
                        if (el.value == '') {
                            continue;
                        }
                        formElements[formElements.length] = el;
                    } 
                    ajaxcart.addToCartHandle(form.action,Form.serializeElements(formElements));
					// ajaxcart.addToCartHandle(form.action,form.serialize());
			} catch (e) {}
			this.form.action = oldUrl;
			if (e) {
				throw e;
			}
		}
	}.bind(productAddToCartForm);
    var productAddToCartFormBak = productAddToCartForm;
</script>
<?php endif; ?>
