<?php
/**
 * Wishlist view
 */
?>
<div id="ajaxcart-my-wishlist">

	<div class="my-wishlist">
	    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	    <?php if ($this->hasWishlistItems()): ?>
	    <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
	        <fieldset>
	            <?php echo $this->getBlockHtml('formkey')?>
	            <table class="data-table" id="wishlist-table">
	            <col width="1" />
	            <col />
	            <col width="1" />
	            <col width="1" />
	            <col width="1" />
	                <thead>
	                    <tr>
	                        <th></th>
	                        <th><?php echo $this->__('Product Details & Comments') ?></th>
	                        <th class="a-center"><span class="nobr"><?php echo $this->__('Add to Bag') ?></span></th>
	                        <th>&nbsp;</th>
	                    </tr>
	                </thead>
	                <tbody>
	                <?php foreach ($this->getWishlistItems() as $item): ?>
	                    <?php
	                        $product = $item->getProduct();
	                        $isVisibleProduct = $product->isVisibleInSiteVisibility();
	                    ?>
	                    <tr>
	                        <td>
	                            <a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->htmlEscape($product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(113, 113); ?>" width="113" height="113" alt="<?php echo $this->htmlEscape($product->getName()) ?>" /></a>
	                        </td>
	                        <td>
	                        	<h2 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a></h2>
	                        	 <?php echo $this->getDetailsHtml($item) ?>
	                            <textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" placeholder="Comments" title="<?php echo $this->__('Comment') ?>"><?php echo $item->description; ?></textarea>
	                        </td>
	                        <td class="a-center add-to-bag-cell">
	                        
	                        <?php if ($item->canHaveQty() && $isVisibleProduct): ?>
	                            <p><input type="text" class="input-text qty" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" /></p>
	                        <?php endif; ?>
	                        
	                        <?php echo $this->getPriceHtml($product) ?>
	                        
	                        <?php if ($product->isSaleable()): ?>
	                            <?php if ($isVisibleProduct): ?>
	                            <button type="button" title="<?php echo $this->__('Add to Bag') ?>" onclick="addWItemToCart(<?php echo $item->getId(); ?>, this)" class="button btn-cart"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button>
	                            <?php endif ?>
	                        <?php else: ?>
	                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                        <?php endif; ?>
	                            
	                          
	                        </td>
	                        <td>
	                            <a href="<?php echo $this->getItemRemoveUrl($item) ?>" title="<?php echo $this->__('Remove Item') ?>" onclick="return confirmRemoveWishlistItem();" class="btn-remove btn-remove2"><?php echo $this->__('Remove item')?></a>
	                        </td>
	                    </tr>
	                <?php endforeach ?>
	                </tbody>
	            </table>
	            <script type="text/javascript">decorateTable('wishlist-table')</script>
	            <div class="buttons-set buttons-set2">
	                <button type="submit" onclick="this.name='save_and_share'" title="<?php echo $this->__('Share Wishlist') ?>" class="button btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
	                <?php if($this->isSaleable()):?>
	                    <button type="button" title="<?php echo $this->__('Add All to Bag') ?>" onclick="addAllWItemsToCart()" class="button btn-add"><span><span><?php echo $this->__('Add All to Bag') ?></span></span></button>
	                <?php endif;?>
	                <button type="submit" title="<?php echo $this->__('Update Wishlist') ?>" onclick="this.name='do'" class="button btn-update"><span><span><?php echo $this->__('Update Wishlist') ?></span></span></button>
	            </div>
	        </fieldset>
	    </form>
	    <?php else: ?>
	        <p><?php echo $this->__('You have no items in your wishlist.') ?></p>
	    <?php endif ?>
	    <script type="text/javascript">
	    //<![CDATA[
	    function confirmRemoveWishlistItem() {
	        return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
	    }
	
	    function focusComment(obj) {
	        if( obj.value == '<?php echo $this->helper('wishlist')->defaultCommentString() ?>' ) {
	            obj.value = '';
	        } else if( obj.value == '' ) {
	            obj.value = '<?php echo $this->helper('wishlist')->defaultCommentString() ?>';
	        }
	    }
	
	    function addWItemToCart(itemId, el) {
	        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
	        url = url.gsub('%item%', itemId);
	        var form = $('wishlist-view-form');
	        if (form) {
	            var input = form['qty[' + itemId + ']'];
	            if (input) {
	                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
	                url += separator + input.name + '=' + encodeURIComponent(input.value);
	            }
	        }
	        
	        /* Ajaxcart Add wishlist product to cart */
	        var proElement = el.up('tr');
	        $('ajaxcart-pop-up').show();
	        var content = $('ajaxcart-content');
	        var pContent = document.createElement('div');
	        pContent.className = 'ajaxcart-preload';
	        content.appendChild(pContent);
	        pContent = content.down('.ajaxcart-preload');
	
	        var productImage = proElement.down('.product-image');
	        if (productImage) {
	            pContent.appendChild(Element.clone(productImage, 1));
	            productImage = pContent.down('img');
	            productImage.width = 120;
	            productImage.height = 120;
	        }
	
	        var productInfo = document.createElement('div');
	        productInfo.className = 'product-info';
	        pContent.appendChild(productInfo);
	        var productName = proElement.down('.product-name');
	        if (productName) productInfo.appendChild(Element.clone(productName, 1));
	        var productPrice = proElement.down('.price-box');
	        if (productPrice) productInfo.appendChild(Element.clone(productPrice, 1));
	
	        pContent.appendChild(Element.clone($('ajaxcart-load-ajax').down('.ajaxcart-loading'), 1));
	
	        ajaxcart.updatePopupBox(content);
	        ajaxcart.addToCartHandle(url,'');
	        // setLocation(url);
	    }
	    
	    Event.observe(window,'load',function(){
	        ajaxcart.wishlistObj = 'ajaxcart-my-wishlist';
	    });
	    
	    function addAllWItemsToCart() {
	        var url = '<?php echo $this->getUrl('*/*/allcart') ?>';
	        var separator = (url.indexOf('?') >= 0) ? '&' : '?';
	        $$('#wishlist-view-form .qty').each(
	            function (input, index) {
	                url += separator + input.name + '=' + encodeURIComponent(input.value);
	                separator = '&';
	            }
	        );
	        setLocation(url);
	    }
	    //]]>
	    </script>
	</div>

</div>

