<?php /** @var Wsnyc_RFC_Block_Pixel $this */?>
<?php if ($this->isEnabled() && $this->isCovnersionEnabled()): ?>

    <!-- Code for Action: The Laundress Universal -->
    <!-- Begin Rocket Fuel Conversion Action Tracking Code Version 9 -->
    <script type='text/javascript'>
        (function() {
            var w = window, d = document;
            var s = d.createElement('script');
            s.setAttribute('async', 'true');
            s.setAttribute('type', 'text/javascript');
            s.setAttribute('src', '//c1.rfihub.net/js/tc.min.js');
            var f = d.getElementsByTagName('script')[0];
            f.parentNode.insertBefore(s, f);
            if (typeof w['_rfi'] !== 'function') {
                w['_rfi']=function() {
                    w['_rfi'].commands = w['_rfi'].commands || [];
                    w['_rfi'].commands.push(arguments);
                };
            }
            _rfi('setArgs', 'ver', '9');
            _rfi('setArgs', 'rb', '<?php echo $this->getUserId(); ?>');
            _rfi('setArgs', 'ca', '<?php echo $this->getConversionPixelId(); ?>');
            _rfi('track');
        })();
    </script>
    <noscript>
        <iframe src='//<?php echo $this->getConversionPixelId(); ?>p.rfihub.com/ca.html?rb=<?php echo $this->getUserId(); ?>&ca=<?php echo $this->getConversionPixelId(); ?>&ra=YOUR_CUSTOM_CACHE_BUSTER' style='display:none;padding:0;margin:0' width='0' height='0'>
        </iframe>
    </noscript>
    <!-- End Rocket Fuel Conversion Action Tracking Code Version 9 -->
<?php endif; ?>