<?php

// get all categories
$helper = Mage::helper('wordpress/category');
$sub_categories_177 = $helper->getSubCategories(177);
$sub_categories_183 = $helper->getSubCategories(183);
$sub_categories_203 = $helper->getSubCategories(203);
$ingredient_pages = $helper->getAllPostsByPostType("ingredients");

// if we are in the main clean & learn category, collapse all sections
$iCurrentCategoryId = (int)$helper->getCurrentContext();

$sCurrentPostTypeId = null;
if(Mage::registry('wordpress_post_type')) {
    // 5 = fabrics, 6 = materials   
    $iCurrentPostTypeId = Mage::registry('wordpress_post_type')->getId();
}

?>
<div class="col-left sidebar grid4-1 grid-col2-sidebar in-sidebar wp-sidebar cleanandlearn">
    <div class="block block-blog block-blog-menu" id="wp-menu-washing">
        <div class="block-title">
            <a href="/blog/category/cleanandlearn/washing-with-gwen-lindsey/" ><strong><span>Washing</span> with Gwen &amp; Lindsey</strong></a>
        </div>        
        <div class="block-content">
            
            <ul>
                <?php ($iCurrentPostTypeId == 5 && $iCurrentPostTypeId != null) ? $class = "active" : $class = "" ?>
            	<li class="level0 nav-1 item odd <?php print $class; ?>"><a href="/blog/byfabric/"><span><?php $label = $helper->filterByTermId($sub_categories_177, 270); echo $label['name']; ?></span></a></li>
            	<?php foreach($sub_categories_177 as $category) : ?>
	            	<?php if($category['term_id'] != 270) : ?>
                                <?php ($category['term_id'] == $iCurrentCategoryId) ? $class = "active" : $class = ""; ?>                                
                                <li class="level0 nav-1 item odd <?php print $class; ?>" ><a href="/blog/category/cleanandlearn/washing-with-gwen-lindsey/<?php echo $category['slug'] ?>"><span><?php echo $category['name'] ?></span></a></li>                               
                        <?php endif ; ?>
                <?php endforeach ; ?>			
            </ul>	            
        </div>        
    </div>
    
    <div class="block block-blog block-blog-menu" id="wp-menu-cleaning">
        <div class="block-title">
            <a href="/blog/category/cleanandlearn/cleaning-with-gwen-lindsey/" ><strong><span>Cleaning</span> with Gwen &amp; Lindsey</strong></a>
        </div>         
        <div class="block-content">
        	<ul>
                <?php ($iCurrentPostTypeId == 6 && $iCurrentPostTypeId != null) ? $class = "active" : $class = "" ?>
                <li class="level0 nav-1 item odd <?php print $class; ?>"><a href="/blog/bymaterial/"><span><?php $label = $helper->filterByTermId($sub_categories_183, 252); echo $label['name']; ?></span></a></li>
            	<?php foreach($sub_categories_183 as $category) : ?>
                    <?php if($category['term_id'] != 252) { ?>
                            <?php ($category['term_id'] == $iCurrentCategoryId) ? $class = "active" : $class = ""; ?>
                            <li class="level0 nav-1 item odd <?php print $class; ?>" ><a href="/blog/category/cleanandlearn/cleaning-with-gwen-lindsey/<?php echo $category['slug'] ?>"><span><?php echo $category['name'] ?></span></a></li>
                    <?php } ?>
                <?php endforeach ; ?>			
            </ul>
        </div>        
    </div>   
    
    <div class="block block-blog block-blog-menu" id="wp-menu-learnmore">
        <div class="block-title">
            <strong><span>Learn More</span></strong>
        </div>       
        <div class="block-content">
            <ul> 
                <li class="level0 nav-1 first item odd"><a href="/blog/category/cleanandlearn/learn-more/ingredients/"><span>OUR INGREDIENTS</span></a>               		 
               		<ul class="level1" id="wp-menu-learnmore-ingredients">
               		
               			<?php foreach($ingredient_pages as $catpage): ?>
               				<li class="level1 nav-2"><a href="<?php echo $catpage->getPermalink() ?>"><span><?php echo $this->escapeHtml($catpage->getPostTitle()) ?></span></a></li>
               			 <?php endforeach; ?>
               			 
                	</ul>
                	
                	</li>
                        <li class="level0 nav-1 first item odd"><a href="/blog/category/cleanandlearn/learn-more/specialty-resources/"><span>SPECIALTY RESOURCES</span></a>

                                <ul class="level1" id="wp-menu-learnmore-resources" >
                                        <?php foreach($sub_categories_203 as $category) : ?>                                    
                                                    <?php ($category['term_id'] == $iCurrentCategoryId) ? $class = "active" : $class = ""; ?>
                                                    <li class="level1 nav-2 <?php print $class; ?>" ><a href="/blog/category/<?php echo $category['slug'] ?>"><span><?php echo $category['name'] ?></span></a></li>
                                                        <?php endforeach ; ?>
                                </ul>

                        </li>

            </ul>	
        </div>     
    </div>   
</div>