<div class="find-store-top">
    <div class="success-message">
        <h1><?php echo $this->__('Find a Store'); ?></h1>
        <p><?php echo $this->__('Enter your address below. To search International stores, enter city.'); ?></p>
        <p class="storelocator-full-width"><?php echo $this->__('*As not all retailers carry our full product selection, please call into the location prior to visiting.'); ?></p>
    </div>
    <div class="find-a-store-form">
        <form action="" method="post" id="store_locator_form" class="custom" onsubmit="return false">
            <button type="submit" title="GO" class="button btn-inline float-right"><span><?php echo strtoupper($this->__('Find a Store')); ?></span></button>
            <div class="float-left postal">
                <label for="address" class=""><?php echo $this->__('City or Zip / Postal Code'); ?></label>
                <input type="text" name="address" id="address" title="<?php echo $this->__('Zip Code/Postal Code'); ?>" class="input-text validate-zip">
            </div> 
            <div class="float-left radius">
                <label for="radius" class=""><?php echo $this->__('Radius'); ?></label>
                <select name="radius" id="radius" form="find-a-store">
                    <option value="5"><?php echo $this->__('5 miles'); ?></option>
                    <option value="10"><?php echo $this->__('10 miles'); ?></option>
                    <option value="20"><?php echo $this->__('20 miles'); ?></option>
                    <option value="50"><?php echo $this->__('50 miles'); ?></option>
                </select>
            </div>
            <div style="clear:both"></div>
        </form>
    </div>
</div>
<div id="find-store-map-area" style="visibility:hidden;"></div>
<div id="storelocator-results" style="visibility:hidden">
    <div id="storelocator-container">
        <div id="find-store-map-results"></div>
    </div>
    <div id="pager-top" class="pager"><?php echo $this->getPagerHtml(); ?></div>
    <div id="pager-bottom" class="pager"><?php echo $this->getPagerHtml(); ?></div>
</div>