<div id="sidebar-contact">
    <div class="block block-vertnav">
        <div class="block-title"><span><?php echo $this->__('Contact') ?></span></div>
        <div class="block-content">
            <ul class="vertnav clearer nav-contact">
            	<li class="first nav-our-story"><a href="/our-story/"><?php echo $this->__('Our Story') ?></a></li>
                <li class="nav-contact-us"><a href="/customer-service/"><span><?php echo $this->__('Customer Service') ?></span></a></li>
                <li class="nav-corporate"><a href="/customer-service/contact-us"><?php echo $this->__('Contact Us') ?></a></li>                
            </ul>
        </div>
    </div>
    <div class="block block-vertnav hide-below-768">
        <div class="block-title"><span><?php echo $this->__('Our Policies') ?></span></div>
        <div class="block-content">
            <ul class="vertnav clearer nav-contact">
                <li class="first nav-faq-orders"><a href="/faq/"> <span><?php echo $this->__('FAQ for Orders') ?></span> </a></li>
                <li class="nav-faq-washing"><a href="/washing-service-faq/"> <span><?php echo $this->__('FAQ for Washing Service') ?></span> </a></li>
                <li class="nav-shipping"><a href="/customer-service/shipping/"><?php echo $this->__('Shipping') ?></a></li>
                <li class="nav-privacy"><a href="/customer-service/privacypolicy/"><?php echo $this->__('Privacy Policy') ?></a></li>
                <li class="nav-terms"><a href="/customer-service/terms/"><?php echo $this->__('Terms & Conditions') ?></a></li>
            </ul>
        </div>
    </div>
</div>
