<script type="text/javascript"> if (!window.mstag) mstag = {loadTag: function () {}, time: (new Date()).getTime()};</script> 
<script id="mstag_tops" type="text/javascript" src="//flex.msn.com/mstag/site/93150bde-0e8d-44dc-9921-c141ee900076/mstag.js"></script> 
<script type="text/javascript"> mstag.loadTag("analytics", {dedup: "1", domainId: "47005800", type: "1", actionid: "267924"})</script> 
<noscript> 
    <iframe src="//flex.msn.com/mstag/tag/93150bde-0e8d-44dc-9921-c141ee900076/analytics.html?dedup=1&domainId=47005800&type=1&actionid=267924" frameborder="0" scrolling="no" width="1" height="1" style="visibility:hidden;display:none"> </iframe> 
</noscript>