<?php

/**
 * Slider for Clean and Learn and all Suncateogries
 * 
 * Slider is deactivated here for subcategories but included on every
 * category within Clean and Learn
 */

// get helper
$helper = Mage::helper('wordpress/category');                                                                      

// id of current category
$iCurrentCategoryId = $helper->getCurrentContext();

// ids of slider activated categories        
$aSliderActive = Array(
    176 => 305,
    180 => 322,
    181 => 325,
    182 => 324,
    309 => 323
);

?>

<div class="page-title">
	<?php if($iCurrentCategoryId == 180) : ?>
	<h1>Style</h1>
	<?php elseif($iCurrentCategoryId == 181) : ?>
	<h1>Culture</h1>
	<?php elseif($iCurrentCategoryId == 182) : ?>
	<h1>Travel</h1>
	<?php elseif($iCurrentCategoryId == 309) : ?>
	<h1>Entertaining</h1>
	<?php endif ; ?>
</div>

<?php if(isset($aSliderActive[$iCurrentCategoryId])) { ?>
<div id="blog-default-slideshow" class="blog-slideshow slideshow-with-details">     
    
        <?php                                     
            $data = $helper->getAllPostsByTag($aSliderActive[$iCurrentCategoryId]);                        
        ?>    
        
        <?php foreach($data AS $post) { ?>            
            <div class="slidesjs-slide">
                <?php if($post->getCustomField('wpcf-slideshow-image')) { ?>                
                <a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
                    <?php
                        $imageHelper = Mage::helper('wordpress/image');
                        $img = $imageHelper->getImageSizeByURL($post->getCustomField('wpcf-slideshow-image'), "post-main-wide");                        
                    ?>
                    <img src="<?php print $img; ?>" />
                </a>
                <?php } else if($post->getFeaturedImage()) { ?>
                <a href="<?php print $post->getPermalink(); ?>" >
                    <img src="<?php print $post->getFeaturedImage()->getImageByType('post-main-wide'); ?>" />
                </a>
                <?php } else { ?>                                
                <a href="<?php print $post->getPermalink(); ?>" >
                    <img src="http://placehold.it/959x424" />
                </a>
                <?php } ?>
                <h2><?php print $post->getPostTitle(); ?></h2>
                <p class="post-date" ><?php print $post->getPostDate(); ?></p>
                
                <p class="entry-summary" >
                    <?php print $post->getExcerpt(); ?>
                </p>
                
                <div class="read-more" >
                    <a href="<?php print $post->getPermalink(); ?>" >Read more</a>
                </div>
            </div>
        <?php } ?>                       
</div>
<?php if(isset($data[1])) { ?>
<script>
    jQuery(function() {
      
      jQuery('#blog-default-slideshow').slidesjs({
        width: 940,
        height: 550,
        navigation: {
          effect: "slide"
        },
        pagination: {
          effect: "slide"
        },
        effect: {
          fade: {
            speed: 400
          }
        },        
        callback: {
            complete: function(number) {
                
                // TODO: Height adaptation
                //var currentSlide = jQuery(
                /*
                 
                #blog-default-slideshow').find("[slidesjs-index='" + (number-1) + "']"); 
                var iNewHeight = currentSlide.height();
                
                if(iNewHeight != null) {
                    jQuery('#blog-default-slideshow').css('height', iNewHeight+1);
                }
                */
            }
        }
      });
    });
  </script>
  <?php } ?>
  
  <?php } ?>