<?php
$rule = Mage::getModel('catalogrule/rule')->load('Flash Promo', 'name');
if ($rule->getId() && $rule->getIsActive()):
?>
<div class="clock"></div>
<script type="text/javascript">
    var remaining = <?php echo strtotime('26-01-2015 16:00') - Mage::getModel('core/date')->timestamp();?>;
    var face = remaining > 3600*24 ? 'DailyCounter' : 'HourlyCounter';
    //var clock = jQuery('.clock').FlipClock(remaining, {clockFace: face, countdown: true});
</script>
<?php endif;?>