<?php $_block = $this->getCmsBlock();?>
<div style='display:none'>
    <div id="page_leave_modal" class="pageleave-popup">
        <div>
            <div>
                <div class="pageleave-cms-content">
                    <?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($_block->getContent()) ?>
                </div>
                <form action="http://thelaundress.us6.list-manage.com/subscribe/post?u=d3d48e75efd637e646b0beb3c&amp;id=dbfb7e7934" method="post" id="mc-embedded-subscribe-form-modal" name="mc-embedded-subscribe-form-modal" class="validate" target="_blank" novalidate="">
                    <div>
                        <input type="email" placeholder="Enter email to redeem*" name="EMAIL" id="mce-EMAIL" value="" title="Email Address" class="input-text required-entry validate-email">
                    </div>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;"><input type="text" name="b_d3d48e75efd637e646b0beb3c_dbfb7e7934" value=""></div>
                    <div class="pageleave-button">
                        <button class="btn button btn-inline" name="subscribe" id="mc-embedded-subscribe-modal">
                            <span>
                                <span><?php echo $this->__('Submit'); ?></span>
                            </span>
                        </button>
                        <span id="no-redeem"><?php echo $this->__('No, thanks. I would rather pay full price.'); ?></span>
                    </div>
                </form>
                <div class="social-media-icon-set">
                    <p class="exclude"><?php echo $this->__('*By entering your email address you are subscribing to receive emails from The Laundress'); ?></p>
                </div>
            </div>
        </div>
    </div>
</div>

<a href="#page_leave_modal" class="openPromoPopup cboxElement"></a>