<div id="story-intro">
	<div class="top">
		<div>
			<a href="#meet-the-founders"><span>Gwen & Lindsey</span> are founders of The Laundress. They are taking the chore out of doing laundry! <span class="link">Meet Our Founders<span></a>
		</div>
		<div><h1>Our Story</h1><div class="small-horizontal-line"></div></div>
		<div>
			<a href="#why-the-laundress"><span>Why The Laundress</span>We offer the most unique product on the market! Discover the magic today! <span class="link">Find Out Why</span></a>
		</div>
	</div>
	<p>Gwen Whiting and Lindsey Boyd weren’t always international soap mavens, delighting fashion-istas, value seekers, and environmentalists from New York to New Delhi. Many laundry cycles ago, they were young fashion enthusiasts, launching careers in one of the world’s best-dressed cities. As Lindsey and Gwen invested in building their wardrobes, they were confronted with the frustration of maintaining them: replacing prematurely worn items and paying painful dry-cleaning bills. As graduates from Cornell University’s Fiber Science, Textile and Apparel Management and Design program, they saw an opportunity to advance the world of fabric care.</p>
	<img src="/skin/frontend/ultimo/default/images/our_story_intro_image.jpg" alt="Gwen and Lindsey" width="373" height="260" border="0" align="right">
</div>

<div class="story-quotes">
	<p class="quote1">&ldquo;We're an eco-friendly line of detergent, fabric care, and home-cleaning products that take excellent care of you, the things you love, and the environment.&rdquo;</p>
	<div class="drycleaning-stat"><p>of items labeled &ldquo;dry clean only&rdquo; are actually washable.</p></div>
	<p class="quote2">&ldquo;Two parts fashion maven + two parts domestic goddess = The Laundress. It’s the most elegant formula for keeping well-loved clothes looking fresh off the hanger.&rdquo;<span>- Daily Candy</span></p>
</div>


<div class="top" id="meet-the-founders">
	<div>
		<a href="#meet-the-founders" class="active"><span>Gwen & Lindsey</span> are founders of The Laundress. They are taking the chore out of doing laundry! <span class="link">Meet Our Founders</span></a>
	</div>
	<div><h1><a href="#story-intro">Our Story</a></h1><div class="small-horizontal-line"></div></div>
	<div>
		<a href="#why-the-laundress"><span>Why Laundress</span>We offer the most unique product on the market! Discover the <br />magic today!<span class="link">Find Out Why</span></a>
	</div>
</div>
<div class="meet-the-founders">
	<div class="gwen">
		<h1>Gwen Whiting</h1>
		<p>Gwen is at the helm of design, product development, and production at The Laundress. When it comes to finding new and innovative ways to improve laundering and home cleaning, she’s not afraid to roll up her beautifully pressed, stain-free sleeves and get her hands dirty.</p>
		<p>Constantly after the best of the best, Gwen finds inspiration in unexpected places such as a market in Provence, a bed and breakfast in the English countryside, and a cheese shop in San Francisco.</p>
		<p>Prior to founding The Laundress, Gwen worked at Ralph Lauren as a senior designer for the Ralph Lauren Home Collection, a position she held for five years. Previously, she worked in Women’s Wear Design and Polo Store Development, also at Ralph Lauren. In her 20s, Gwen’s passion for fabric and fashion took her all over the globe, from India to Argentina.</p>
		<h2>Most treasured item from wardrobe</h2>
		<p>Both my grandmothers collected beautiful hankies. I have a special few, including one that features the lost art of hand-tatting.</p>
		<h2>Laundry pet peeve</h2>
		<p>When people spill while at a restaurant and make the stain worse by treating it with water and napkins. The best thing to do (honestly!) is to enjoy a glass of wine and take care of it later.</p>
		<h2>Favorite Laundress product</h2>
		<p>My favorite is our Stain Solution. I use it with every wash. When I say it gets everything out, I really mean everything.</p>
		<h2>Proudest laundry victory</h2>
		<p>Every time I remove a tough stain, I experience a little victory! I can’t tell you how many times my friends have called me in the midst of stain crises and I’ve FedExed them a bottle of our Stain Solution. It never fails to save the day.</p>
	</div>
	<div class="lindsey">
		<h1>Lindsey Boyd</h1>
		<p>With her finger on the pulse of the retail industry, Lindsey serves as the resident sales and marketing expert for The Laundress. Over the years, she has forged a range of relationships with diverse sales partners throughout the world. Lindsey brings The Laundress experience to delighted customers near and far.</p>
		<p>Before founding The Laundress, Lindsey was the manager of U.S. sales for Chanel Ready-to-Wear, where she trained and managed boutique and large wholesale accounts. Prior to her tenure at Chanel, Lindsey worked in product development and corporate sales for Brooks Brothers.</p>
		<p>Creative and entrepreneurial from an early age, Lindsey previously designed and marketed her own line of T-shirts that were sold at stores such as Saks Fifth Avenue and Henri Bendels.</p>
		<h2>Most treasured item from wardrobe</h2>
		<p>My first Chanel jacket, bought in 2000—a timeless piece that I still wear, love, and wash.</p>
		<h2>Laundry pet peeve</h2>
		<p>Wrinkled clothing! Unless it’s linen, in which case I give anyone a free pass.</p>
		<h2>Favorite Laundress product</h2>
		<p>I really love our Delicate Wash, especially for silk dresses, blouses, and scarves. This is my “go to” product for 75% of my wardrobe, allowing me to bypass the dry cleaner.</p>
		<h2>Proudest laundry victory</h2>
		<p>Removing an entire glass of wine from my sofa during a party. My friends watched in amazement as the stain came right out. Some new believers were born that day!</p>
	</div>
</div>

<div class="top" id="why-the-laundress">
	<div>
		<a href="#meet-the-founders"><span>Gwen & Lindsey</span> are founders of The Laundress. They are taking the chore out of doing laundry! <span class="link">Meet Our Founders</span></a>
	</div>
	<div><h1><a href="#story-intro">Our Story</a></h1><div class="small-horizontal-line"></div></div>
	<div>
		<a class="active" href="#why-the-laundress"><span>Why The Laundress</span>We offer the most unique product on the market! Discover the <br />magic today! <span class="link">Find Out Why</span></a>
	</div>
</div>
<div class="why-the-laundress">
	<div class="save">
		<h2>Save Money</h2>
		<div>
			<img src="/skin/frontend/ultimo/default/images/save_1.gif" alt="" width="256" height="156" border="0" align="left">
			<p>You save <span><sub>$</sub>108.20</span> For <b>20 items</b></p>
		</div>
		<div>
			<p>You'll use fewer ounces of detergent per load, <b>extending</b> the use of each bottle and saving you money over time.</p>
		</div>
	</div>
	<div class="green">
		<h2>We're Green</h2>
		<div>
			<img src="/skin/frontend/ultimo/default/images/green_1.gif" alt="" width="192" height="113" border="0" align="left">
			<p><span>100%</span>BIODEGRADABLE</p>
			<p><b>Nontoxic:</b> No allergens, Phthalate, Phosphate, Paraben or Bleach.</p>
		</div>
		<div class="green-split">
			<div>
				<p><span>NATURAL</span> SCENTS & COLORS</p>
				<p>Allergen & Gluten-free</p>
			</div>
			<div>
				<p><span>RECYCLED</span> PACKAGING</p>
				<p>We also <b>recycle</b> all our shipping materials.</p>
			</div>
		</div>
		<div class="cruelty-free">
			<p><span>CRUELTY-FREE</span>Our products are tested on <b>Gwen and Lindsey</b>, not on animals.</p>
		</div>
	</div>
	<h1>Why The <span>Laundress?</span></h1>
	<div class="easy">
		<h2>Easy to use</h2>
		<div>
			<p>Laundress products are <b>suited</b> to all machines, washing temperatures, and water systems.</p>
		</div>
		<div>
			<p>All our products are <b>color safe</b> No need to second-guess</p>
		</div>
	</div>
	<div class="neurotic">
		<h2>We're Neurotic, in a good way</h2>
		<div>
			<p>Each of our products is <b>Specially designed</b> for individual fabrics using the most effective ingredients.</p>
		</div>
	</div>
</div>

<div class="closing-quote">
	<p>&ldquo;With a little bit of knowledge&#8230; it is possible to have a <i>long-term, low-maintenance relationship</i> with cashmere. Gwen Whiting and Lindsey Boyd are two New Yorkers who left their jobs in fashion to educate the new cashmere-wearing constituency about how best to treat their jumpers.&rdquo;<span>– The Daily Telegraph</span></p>
</div>
