<?php $richSnippets = $this->getAddRichSnippets(); ?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings" <?php if($richSnippets): ?>itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating"<?php endif; ?>>
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
            <?php if($richSnippets): ?>
              <meta itemprop="worstRating" content = "1">
              <meta itemprop="ratingValue" content="<?php echo round($this->getRatingSummary()/20,1); ?>" />
              <meta itemprop="bestRating" content = "5">             
            <?php endif; ?>            
        <?php endif;?>
        <?php $reviewCount = $richSnippets ? '<span itemprop="reviewCount">'.$this->getReviewsCount().'</span>' : $this->getReviewsCount(); ?>
        <span class="amount"><a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%s Review(s)',$reviewCount) ?></a></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
