<div class="grid4-2 left">
    <div class="contact-info">
        <h3>The Laundress, Inc</h3>
        <address>247&nbsp;W.&nbsp;30th&nbsp;Street,&nbsp;2R<br>New York, NY 10001</address>
        <p>Tel: <span>212-209-0074</span><span class="spacer">|</span>Fax: <span>775-213-7158</span> <a href="mailto:laundress@thelaundress.com" class="email">Laundress@TheLaundress.com</a></p>
    </div>
    <div class="international-q">
    	<h3>International order questions:</h3>
		<p>Please contact INTERNATIONAL CHECKOUT <a href="mailto:Support@InternationalCheckout.com" class="email">Support@InternationalCheckout.com</a></p>
    </div>
    
    <div class="box-note"><span>PLEASE NOTE:</span> The Laundress ships worldwide so please e-mail us if you cannot order online to place your order.</div>
</div>

<div class="grid4-2 right">
	<div class="wholesale">
		<h3>Wholesale Inquiries:</h3>
	    <p><a class="mailto:Sales@TheLaundress.com" class="email">Sales@TheLaundress.com</a></p>
	</div>
    <div class="press">
    	<h3>THE LAUNDRESS PRESS:</h3>
	    <p><a href="mailto:Press@TheLaundress.com" class="email">Press@TheLaundress.com</a><br><a id="download-presskit" class="download" href="/presskit">PRESS KIT</a><br><a id="download-presskit" class="download" href="/presskit">INFORMATION FOR PRESS</a></p>
    </div>
    <div class="distribution">
    	<h3>Contact THE LAUNDRESS ABOUT DISTRIBUTION:</h3>
	    <p><a href="mailto: International@TheLaundress.com" class="email"> International@TheLaundress.com</a><br>Tel: <span>212-209-0074</span></p>
    </div>
</div>

