<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item post-list-item-fabric">
	<?php if ($featuredImage = $post->getFeaturedImage()): ?>
		<div class="featured-image">
			<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
            <img src="<?php echo $featuredImage->getAvailableImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
		</div>
	<?php endif; ?>	
	<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>	
	<div class="post-entry entry">
		<?php echo $post->getPostExcerpt() ?>
	</div>
	<div class="post-action-bar">		
		
		<a href="<?php echo $post->getPermalink() ?>" class="post-read-more">Wash Now</a>
	</div>
	<!--<?php echo $this->getMetaBlock()->setPost($post)->toHtml() ?>
	<?php if ($this->helper('wordpress/plugin_shareThis')->canDisplayOnPost()): ?>
		<div class="sharethis-icons" id="sharethis-icons-<?php echo $post->getId() ?>"><?php echo $this->helper('wordpress/plugin_shareThis')->getIcons($post) ?></div>
	<?php endif; ?>-->
</div>