<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>

<div class="ask-post">
	<span class="ask-category"><?php echo $post->getParentCategory()->name ?></span>
	<span class="ask-title"><?php echo $this->escapeHtml($post->getPostTitle()) ?></span>
	<p><?php echo $post->getPostExcerpt() ?></p>
	<a class="ask-read-more" href="<?php echo $post->getPermalink() ?>">Read more</a>
</div>