<?php foreach($this->getModals() as $modal): ?>

    <?php Mage::getSingleton('core/cookie')->set('modal-' . $modal->getId(), '1' ,time()+31536000,'/'); ?>
    <div style="display:none">
        <div id="modal_<?php echo $modal->getId() ?>" class="promotion-modal">
            <div>
                <div>
                    <div class="logo-wrapper v-item">
                        <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><?php echo $this->getLogoAlt() ?></a></h1>
                    </div>
                    <h3><?php echo $modal->getModalName() ?></h3>
                    <div>
                        <?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($modal->getModalDescription()) ?>
                    </div>

                    <div class="call-us-message">
                        <p><?php echo $this->__('Please call us at (212) 209-0074 with any questions.'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(function($) {
            jQuery('a[href="#modal_<?php echo $modal->getId() ?>"]').colorbox({
                inline  : true,
                opacity : 0.5,
                speed   : 300,
                width   : 510,
                height  : 500,
                closeButton : true,
                className: 'promomodals_box modal_content_<?php echo $modal->getId() ?>',
                onCleanup: function() {
                    jQuery('#modal_<?php echo $modal->getId() ?>').parent().siblings( "#cboxClose" ).attr('class','noclass');
                },
                onComplete: function() {
                    jQuery('#modal_<?php echo $modal->getId() ?>').parent().siblings( "#cboxClose" ).attr('class','modal-close');
                },
                
            });
        });
    </script>
<?php endforeach; ?>

    