<?php $block = Mage::getModel('cms/block')->load('modal-freeshipping-info'); ?>
<?php if(Mage::getStoreConfig('wsnyc_promotions/promotions/freeshipping_may_2014_enabled')): ?>
    <?php $cookie = Mage::getSingleton('core/cookie'); ?>
    <?php $cookie->set('free-shipping-info', '1' ,time()+31536000,'/'); ?>
    <div style='display:none'>
        <div id="inline_freeshipping_colorbox" class="freeshipping-popup">
            <div>
                <div>
                    <div class="logo-wrapper v-item">
                        <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><?php echo $this->getLogoAlt() ?></a></h1>
                    </div>
                    <h3>Free Shipping Details</h3>
                    <div class="freeshipping-cms-content">
                        <?php echo $block->getContent() ?>
                    </div>

                    <div class="call-us-message">
                        <p><?php echo $this->__('Please call us at (212) 209-0074 with any questions.'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(function($) {
            $(".openFreeshippingPopup").colorbox({
                inline  : true,
                opacity : 0.5,
                speed   : 300,
                width   : 510,
                height  : 460,
                closeButton : true,
                className: 'freeshipping-colorbox',
                onCleanup: function() {
                    jQuery('#inline_freeshipping_colorbox').parent().siblings( "#cboxClose" ).attr('class','noclass');
                },
                onComplete: function() {
                    jQuery('#inline_freeshipping_colorbox').parent().siblings( "#cboxClose" ).attr('class','modal-close');
                },
                
            });
        });
    </script>
<?php endif; ?>

    