<?php if(Mage::getStoreConfig('wsnyc_promotions/promotions/photocontest_june_2014_enabled')): ?>
    <?php $block = Mage::getModel('cms/block')->load('modal-photocontest_june_2014'); ?>
    <?php Mage::getSingleton('core/cookie')->set('modal-photocontest_june_2014', '1' ,time()+31536000,'/'); ?>
    <div style="display:none">
        <div id="modal_photocontest_june_2014" class="promotion-modal">
            <div>
                <div>
                    <div class="logo-wrapper v-item">
                        <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><?php echo $this->getLogoAlt() ?></a></h1>
                    </div>
                    <h3><?php $this->__('The Laundress Wash & Win Photo Contest') ?></h3>
                    <div class="freeshipping-cms-content">
                        <?php echo Mage::helper('cms')->getBlockTemplateProcessor()->filter($block->getContent()) ?>
                    </div>

                    <div class="call-us-message">
                        <p><?php echo $this->__('Please call us at (212) 209-0074 with any questions.'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(function($) {
            jQuery('a[href="#modal_photocontest_june_2014"]').colorbox({
                inline  : true,
                opacity : 0.5,
                speed   : 300,
                width   : 510,
                height  : 460,
                closeButton : true,
                className: 'photocontest_june_2014',
                onCleanup: function() {
                    jQuery('#modal_photocontest_june_2014').parent().siblings( "#cboxClose" ).attr('class','noclass');
                },
                onComplete: function() {
                    jQuery('#modal_photocontest_june_2014').parent().siblings( "#cboxClose" ).attr('class','modal-close');
                },
                
            });
        });
    </script>
<?php endif; ?>

    