<?php
    Mage::register('chart_package', 'geochart')
?>
<script type="text/javascript">
    function drawChart()
    {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Popularity'],
          ['Germany', 200],
          ['United States', 300],
          ['Brazil', 400],
          ['Canada', 500],
          ['France', 600],
          ['RU', 700]
        ]);

        var data = google.visualization.arrayToDataTable(<?php echo json_encode($this->getSeries()) ?>);

        

        var options = {};

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));

        google.visualization.events.addListener(chart, 'ready', function () {
            export_link.href = chart.getImageURI();
        });

        chart.draw(data, options);
    }
</script>

<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;">Save chart as an image</a>
<div id="chart_div" style="widht: 100%; height: 500px;"></div>