<h2> All The Tips &amp; Tools You Need...</h2>
<p class="header-copy">As of Monday, November 24th, we will no longer offer our washing service. While we have truly enjoyed caring for your clothing, linens, and even stuffed animals over the years, we are confident that with our tools and instructions you can care for your items in true Laundress fashion in your own home! After all, we’ve developed our detergents, fabric care, and easy step-by-step laundering instructions just for you.</p>
<p class="header-copy">Need assistance choosing the perfect product or recommendations for washing that valuable vintage piece? We’re glad to walk you through the process! Call us at 212-209-0074 or email us at <a href="mailto:askthelaundress@thelaundress.com">askthelaundress@thelaundress.com</a> with all of your laundering questions.</p>
<h3>A little taste of our How To's & Ask The Laundress Q&amp;A...</h3>
<ul class="washing-service-list">
    <li>
        <a href="http://blog.thelaundress.com/wordpress/2014/09/16/how-to-wash-wool-cashmere/">
            <img src="<?php echo $this->getSkinUrl('images/washing-service-wool-wash.jpg');?>" />
            <span>How To Wash Wool & Cashmere</span>
        </a>
    </li>
    <li>
        <a href="http://blog.thelaundress.com/wordpress/2014/07/21/how-to-remove-the-dreaded-pit-stain/">
            <img src="<?php echo $this->getSkinUrl('images/washing-service-pit-stains.jpg');?>" />
            <span>How To Remove Pit Stains</span>
        </a>
    </li>
    <li>
        <a href="http://blog.thelaundress.com/wordpress/2014/06/25/product-spotlight-sport-detergent-sport-spray/">
            <img src="<?php echo $this->getSkinUrl('images/washing-service-wash-activewear.jpg');?>" />
            <span>How To Wash Activewear</span>
        </a>
    </li>
    <li>
        <a href="http://blog.thelaundress.com/wordpress/2014/06/24/how-to-care-for-swimwear/">
            <img src="<?php echo $this->getSkinUrl('images/washing-service-wash-swimsuits.jpg');?>" />
            <span>How To Wash Swimsuits</span>
        </a>
    </li>
    <li>
        <a href="http://www.thelaundress.com/asklaundress/">
            <img src="<?php echo $this->getSkinUrl('images/washing-service-ask-the-laundress.jpg');?>" />
            <span>Ask The Laundress</span>
        </a>
    </li>
</ul>