<?php $iCurrentCategoryId = Mage::registry('wordpress_category'); ?>
<?php if($iCurrentCategoryId->getId() == '183') { ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cleanandlearn_cleaning_top')->toHtml() ?>

<div class="top_block_text">                        
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cleanandlearn_cleaning_top_text')->toHtml() ?>
</div>
<?php } ?>