<div class="blog-fabrics-atoz" >
    <ul>
        <li><a href="/blog/byfabric?fabric=A">A</a></li>
        <li><a href="/blog/byfabric?fabric=B">B</a></li>
        <li><a href="/blog/byfabric?fabric=C">C</a></li> 
        <li><a href="/blog/byfabric?fabric=D">D</a></li> 
        <li><a href="/blog/byfabric?fabric=E">E</a></li> 
        <li><a href="/blog/byfabric?fabric=F">F</a></li> 
        <li><a href="/blog/byfabric?fabric=G">G</a></li> 
        <li><a href="/blog/byfabric?fabric=H">H</a></li> 
        <li><span style="color:#BCBCBC">I</span></li> 
        <li><a href="/blog/byfabric?fabric=J">J</a></li> 
        <li><a href="/blog/byfabric?fabric=K">K</a></li> 
        <li><a href="/blog/byfabric?fabric=L">L</a></li> 
        <li><a href="/blog/byfabric?fabric=M">M</a></li> 
        <li><a href="/blog/byfabric?fabric=N">N</a></li> 
        <li><span style="color:#BCBCBC">O</span></li> 
        <li><a href="/blog/byfabric?fabric=P">P</a></li> 
        <li><span style="color:#BCBCBC">Q</span></li> 
        <li><a href="/blog/byfabric?fabric=R">R</a></li> 
        <li><a href="/blog/byfabric?fabric=S">S</a></li> 
        <li><a href="/blog/byfabric?fabric=T">T</a></li> 
        <li><span style="color:#BCBCBC">U</span></li>
        <li><a href="/blog/byfabric?fabric=V">V</a></li>
        <li><a href="/blog/byfabric?fabric=W">W</a></li>
        <li><span style="color:#BCBCBC">X</span></li>
        <li><a href="/blog/byfabric?fabric=Y">Y</a></li>
        <li><span style="color:#BCBCBC">Z</span></li>
    </ul>    
</div>