<div class="blog-fabrics-atoz" >
    <ul>
        <li><a href="/blog/bymaterial?material=A">A</a></li>
        <li><a href="/blog/bymaterial?material=B">B</a></li>
        <li><a href="/blog/bymaterial?material=C">C</a></li> 
        <li><a href="/blog/bymaterial?material=D">D</a></li> 
        <li><a href="/blog/bymaterial?material=E">E</a></li> 
        <li><a href="/blog/bymaterial?material=F">F</a></li> 
        <li><a href="/blog/bymaterial?material=G">G</a></li> 
        <li><a href="/blog/bymaterial?material=H">H</a></li> 
        <li><a href="/blog/bymaterial?material=I">I</a></li> 
        <li><a href="/blog/bymaterial?material=J">J</a></li> 
        <li><a href="/blog/bymaterial?material=K">K</a></li> 
        <li><a href="/blog/bymaterial?material=L">L</a></li> 
        <li><a href="/blog/bymaterial?material=M">M</a></li> 
        <li><a href="/blog/bymaterial?material=N">N</a></li> 
        <li><a href="/blog/bymaterial?material=O">O</a></li> 
        <li><a href="/blog/bymaterial?material=P">P</a></li> 
        <li><a href="/blog/bymaterial?material=Q">Q</a></li>
        <li><a href="/blog/bymaterial?material=R">R</a></li> 
        <li><a href="/blog/bymaterial?material=S">S</a></li> 
        <li><a href="/blog/bymaterial?material=T">T</a></li> 
        <li><a href="/blog/bymaterial?material=U">U</a></li>
        <li><a href="/blog/bymaterial?material=V">V</a></li>
        <li><a href="/blog/bymaterial?material=W">W</a></li>
        <li><a href="/blog/bymaterial?material=X">X</a></li>
        <li><a href="/blog/bymaterial?material=Y">Y</a></li>
        <li><a href="/blog/bymaterial?material=Z">Z</a></li>
    </ul>    
</div>
