<?php
/* @var $this Rejoiner_Acr_Block_Snippets */
?>

<?php if (Mage::helper('checkout/cart')->getCart()->getSummaryQty()):?>
<?php $items = $this->getCartItems() ?>

    <script type="text/javascript">
        var _rejoiner = _rejoiner || [];
        _rejoiner.push(["setAccount", "<?php echo $this->helper('rejoiner_acr')->getRejoinerSiteId() ?>"]);
        _rejoiner.push(["setDomain", "<?php echo $this->helper('rejoiner_acr')->getDomain() ?>"]);

        <?php if ($this->helper('rejoiner_acr')->getTrackNumberEnabled()):?>
            _rejoiner.push(["trackNumbers"]);
        <?php endif ?>

        <?php if ($this->helper('rejoiner_acr')->getPersistFormsEnabled()):?>
            _rejoiner.push(["persistForms"]);
        <?php endif ?>
        (function() {
            var s = document.createElement('script'); s.type = 'text/javascript';
            s.async = true; s.src = 'https://s3.amazonaws.com/rejoiner/js/v3/t.js';
            var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
        })();
    </script>

    <script type="text/javascript">
     <?php
     $cartData = $this->getCartData();
     $cartData .= ($this->getChildHtml('rejoiner_email'))? ' ,'.$this->getChildHtml('rejoiner_email'): '';?>
     <?php if (Mage::getStoreConfig('checkout/rejoiner_acr/coupon_code')):?>
     <?php $couponCode = $this->helper('rejoiner_acr')->generateCouponCode();
          $cartData .= ','.'"promo"'.':'.'"'.$couponCode.'"';?>
     <?php endif; ?>
     _rejoiner.push(["setCartData", <?php echo $cartData? "{". $cartData . "}" : ''?>]);
    <?php foreach ($items as $item): ?>
        <?php $itemsAsJson = Mage::helper('core')->jsonEncode($item); ?>
        <?php $itemsAsJson = str_replace('\\', '', $itemsAsJson); ?>
        _rejoiner.push(["setCartItem", <?php echo $itemsAsJson?>]);
    <?php endforeach ?>
    </script>
<?php endif ?>