<?php
/**
 * Block displaying SEO blurb
 * 
 * @var Wsnyc_SeoSubfooter_Block_Footer $this
 */
?>
<?php if ($this->shouldShowBlurb()): ?>
<div class="blurb std container">
    <h4>
    <?php if ($this->getBlurb()->getUrl()):?>
        <a href="<?php echo $this->getBlurb()->getUrl();?>"><?php echo $this->getBlurb()->getTitle();?></a>
    <?php else: ?>
        <?php echo $this->getBlurb()->getTitle();?>
    <?php endif; ?>        
    </h4>
    <div>
        <?php echo $this->getBlurb()->getFilteredContent();?>
    </div>
</div>
<?php endif; ?>

