<?php
$_v = $this->getVendor();
?>

<?php switch ($this->getPart()): case 'header': ?>

<tr class="udropship-cart-vendor-header">
    <td colspan="10" style="padding-top:5px; padding-bottom:0">
    <?php if ($_v->getId()): ?>
        <h3><?php echo $_v->getVendorName() ?></h3>
    <?php else: ?>
        <h3>Unknown vendor</h3>
    <?php endif ?>
    <?php $vendorErrors = $this->getQuote1()->getMinVendorOrderAmountErrors(); ?>
    <?php if (!empty($vendorErrors) && !empty($vendorErrors[$_v->getId()])): ?>
        <p class="item-msg error">* <?php echo $this->htmlEscape($vendorErrors[$_v->getId()]) ?></p>
    <?php endif ?>
    </td>
</tr>
<tr class="heading-row">
    <th colspan="3">Product</th>
    <th>Unit Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
</tr>
<?php break; case 'footer': ?>


<?php endswitch ?>