<h1 class="page_title">Ask The Laundress</h1>
<h2>Got a mysterious stain or a truly terrible laundry&nbsp;quandary? </h2>
<p>Send Us your questions* and we will provide answers!<br>
    &nbsp;<br>
</p>
<form id="questionsanswers-question-ask-form" name="ask-question-box" method="post" action="">
    <input type="text" name="ask_name" id="ask_name" required placeholder="Your Name" />
    <input type="text" name="ask_email" id="ask_email" required placeholder="Your Email" />
    <input type="text" name="ask_title" id="ask_title" required placeholder="Question Title" />
    <span style="display:none" id="ask_title_error">A title is required</span>
    <textarea id="ask_text" name="question_text" required></textarea>
    <span style="display:none" id="ask_text_error">A message is required</span>
    <div class="clearfix"><br/></div>
    <p><img id="ask-loader" src="/skin/frontend/ultimo/default/images/ajax-loader.gif"><input type="submit" id="ask-question-submit" value="ASK QUESTION"></p>
</form>
<br/>
<em>*Be sure to include what you can of the fabric &amp; stain type, as well as relevant washing history.</em>