<?php echo $this->getChildHtml('wsnyc_questionsanswers_topmenu'); ?>

<div id="wsnyc-questionsanswers-container" class="js-masonry"
     data-masonry-options='{ "columnWidth": 287, "itemSelector": ".item" }'>
<?php $categories = $this->getCategoryCollection(); ?>
<?php foreach($categories as $cat): ?>
    <div class="wsnyc-questionsanswers-category item">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wsnyc_questionsanswers/'.$cat->getImage() ?>" alt="<?php echo $cat->getName() ?>" />
    <h4><?php echo $cat->getName() ?></h4>
        <ul>
    <?php foreach($cat->getSubcategoriesCollection() as $subcat): ?>
        <li><a href="<?php echo $subcat->getUrlRewrite();//Mage::getUrl('asklaundress/questions',array('id'=>$subcat->getId())) ?>"><?php echo $subcat->getName() ?></a></li>
    <?php endforeach; ?>
        </ul>
    </div>
<?php endforeach; ?>
</div>