<?php $questions = $this->getQuestions() ?>
<?php $categoryUrls = array(); ?>

<?php if($questions->count()): ?>
    <?php foreach($questions as $question): ?>
        <div class="search-answer">
            <?php
            if(!$categoryUrls[$question->getCategoryId()]){
                $category =Mage::getModel('wsnyc_questionsanswers/category')->load($question->getCategoryId());
                $categoryUrls[$question->getCategoryId()] = $category->getUrlRewrite();
            }
            ?>
            <a href="<?php echo $categoryUrls[$question->getCategoryId()]; ?>#q<?php echo $question->getId() ?>"><?php echo $question->getQuestionText(); ?></a>
        </div>
    <?php endforeach; ?>
<?php endif; ?>