<h1 class="wsnyc-questionsanswers-middle wsnyc-questionsanswers-title">Ask the Laundress</h1>
<div class="wsnyc-questionsanswers-button first"><a href="/asklaundress/questions/ask">Ask a Question</a></div>
<div class="wsnyc-questionsanswers-button"><a href="/asklaundress">View Archives</a></div>
<div class="wsnyc-questionsanswers-button">Recent Questions</div>
<div class="wsnyc-questionsanswers-button">Videos</div>

<div class="wsnyc-questionsanswers-searchholder">
    <form action="/asklaundress/questions/search" method="post">
        <input class="wsnyc-questionsanswers-search" name="questionsanswersquery" placeholder="Search Ask The Laundress" />
    </form>
</div>