<h1 class="wsnyc-questionsanswers-middle wsnyc-questionsanswers-title">Ask the Laundress</h1>
<div class="wsnyc-questionsanswers-button first"><a href="/asklaundress/questions/ask">Ask a Question</a></div>
<div class="wsnyc-questionsanswers-button"><a href="/asklaundress">View All Ask The Laundress</a></div>
<?php /* Use visibility:hidden until these tabs are given content, to avoid disrupting the page layout */ ?>
<div class="wsnyc-questionsanswers-button" style="visibility: hidden;">Recent Questions</div>
<div class="wsnyc-questionsanswers-button" style="visibility: hidden">Videos</div>

<div class="wsnyc-questionsanswers-searchholder">
    <form action="/asklaundress/questions/search" method="post">
        <input class="wsnyc-questionsanswers-search" name="questionsanswersquery" placeholder="Search Ask The Laundress" />
    </form>
</div>
