<div class="challenge">
    <a title="Spring Cleaning Bundle" href="<?php echo $this->getUrl('spring-cleaning-bundle');?>">
        <img title="Pick up the Spring Cleaning Bundle" src="<?php echo $this->getUrl('media/wysiwyg/30daychallenge') . 'icon.jpg'; ?>" alt="Spring Clean Bundle"/>
    </a>
    <span>
        The <a title="Spring Cleaning Bundle" href="<?php echo $this->getUrl('spring-cleaning-bundle');?>">Spring Cleaning Bundle</a> includes
        All-Purpose Cleaning Concentrate, Scented Vinegar, Signature Detergent, Stain Solution, All-Purpose Bleach Alternative,
        Stain Brush and Black & White Shopper.
    </span>
</div>